title: vCard - Personal Portfolio
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
collections:
  projects:
    output: true
  testimonials:
    output: true
author:
  name: "Richard Hanrick"
  birthday: "1982-06-23"
  location: "Sacramento, California, USA"
  position: "Web developer"
  email: "richard@example.com"
  phone: "+12133522795"
  social:
    twitter: "https://twitter.com/codewithsadee"
    facebook: "https://www.facebook.com/codewithsadee"
    instagram: "https://www.instagram.com/codewithsadee"
plugins:
  - jekyll-feed
exclude:
  - .idea
  - README.md
