- title: "Web design"
  description: "The most modern and high-quality design made at a professional level."
  imageURL: "/assets/images/icon-design.svg"

- title: "Web development"
  description: "High-quality development of sites at the professional level."
  imageURL: "/assets/images/icon-dev.svg"

- title: "Mobile apps"
  description: "Professional development of applications for iOS and Android."
  imageURL: "/assets/images/icon-app.svg"

- title: "Photography"
  description: "I make high-quality photos of any category at a professional level."
  imageURL: "/assets/images/icon-photo.svg"